language: python
sudo: required
dist: trusty
branches:
  only:
    - master
install:
  - sudo apt-get update -qq
  - sudo apt-get install python-clang-3.5 libclang-3.5-dev python-dev cython python-numpy python-nose python-coverage -qq
script: nosetests
