language: generic
sudo: required
dist: trusty
cache:
  apt: true
virtualenv:
  system_site_packages: true

branches:
  only:
    - master

install:
  - sudo apt-get update -qq
  - sudo apt-get install python python-dev python-clang-3.5 libclang-3.5-dev python-numpy cython python-nose python-coverage -qq

script: nosetests
