__version__ = "0.0"
__description__ = "Generate Cython wrapper for C++ code automatically."
__author__ = "Alexander Fabisch"
__author_email__ = "afabisch@googlemail.com"
__url__ = "https://github.com/AlexanderFabisch/cythonwrapper"
